### ISSUE TITLE
Withdraw operation throws error

### ISSUE THREAD

**Issue by kykungz** [OOP2018/coinpurse-wisaTong#2]
Steps:
1. Deposit: `10` `5` `2` ✅
3. Check balance:  `Purse contains 17.00 Baht` ✅
2. Withdraw: `8` ❌
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:422)
	at java.util.ArrayList.get(ArrayList.java:435)
	at coinpurse.Purse.withdraw(Purse.java:102)
	at coinpurse.ConsoleDialog.withdrawDialog(ConsoleDialog.java:111)
	at coinpurse.ConsoleDialog.run(ConsoleDialog.java:52)
	at coinpurse.Main.main(Main.java:21)
```

**Comment by kykungz** [comment]
My fault.
